const router = require("express").Router();

const adminRoutes = require("./adminRoutes");
const bookingRoutes = require("./bookingRoutes");
const cartRoutes = require("./cartRoutes");
const cart_itemRoutes = require("./cart_itemRoutes");
const countryRoutes = require("./countryRoutes");
const customerRoutes = require("./customerRoutes");
const customer_addressRoutes = require("./customer_addressRoutes");
const customer_cardRoutes = require("./customer_cardRoutes");
const delivery_methodRoutes = require("./delivery_methodRoutes");
const discountRoutes = require("./discountRoutes");
const districtRoutes = require("./districtRoutes");
const eventRoutes = require("./eventRoutes");
const event_typeRoutes = require("./event_typeRoutes");
const flatRoutes = require("./flatRoutes");
const genderRoutes = require("./genderRoutes");
const human_categoryRoutes = require("./human_categoryRoutes");
const langRoutes = require("./langRoutes");
const payment_methodRoutes = require("./payment_methodRoutes");
const regionRoutes = require("./regionRoutes");
const seatRoutes = require("./seatRoutes");
const seat_typeRoutes = require("./seat_typeRoutes");
const sectorRoutes = require("./sectorRoutes");
const ticketRoutes = require("./ticketRoutes");
const ticket_statusRoutes = require("./ticket_statusRoutes");
const ticket_typeRoutes = require("./ticket_typeRoutes");
const typesRoutes = require("./typesRoutes");
const venueRoutes = require("./venueRoutes");
const venue_photoRoutes = require("./venue_photoRoutes");
const venue_typesRoutes = require("./venue_typesRoutes");

router.use(adminRoutes);
router.use(bookingRoutes);
router.use(cartRoutes);
router.use(cart_itemRoutes);
router.use(countryRoutes);
router.use(customerRoutes);
router.use(customer_addressRoutes);
router.use(customer_cardRoutes);
router.use(delivery_methodRoutes);
router.use(discountRoutes);
router.use(districtRoutes);
router.use(eventRoutes);
router.use(event_typeRoutes);
router.use(flatRoutes);
router.use(genderRoutes);
router.use(human_categoryRoutes);
router.use(langRoutes);
router.use(payment_methodRoutes);
router.use(regionRoutes);
router.use(seatRoutes);
router.use(seat_typeRoutes);
router.use(sectorRoutes);
router.use(ticketRoutes);
router.use(ticket_statusRoutes);
router.use(ticket_typeRoutes);
router.use(typesRoutes);
router.use(venueRoutes);
router.use(venue_photoRoutes);
router.use(venue_typesRoutes);

module.exports = router;
